# Generated by Django 5.1.5 on 2025-02-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bookreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookReview',
            new_name='Book',
        ),
    ]
